[agent]
name = "demodata"

[all]
external_paths=["./agents/demodata/frontend_data"]

[[actors]]
name="frontend_data"
push="./agents/demodata/frontend_data:/code"
wit="external:frontend_data_queries:app"
wit_query="external:frontend_data_queries:app"