[agent]
name = "jetpack"

[all]
external_paths=["./agents/jetpack/frontend", "./agents/jetpack/chat", "./agents/jetpack/coder"]

[[actors]]
name="frontend"
push=["./agents/jetpack/frontend/index.html:/templates/index.html"]
wit_genesis="external:agents.jetpack.frontend.frontend_wit:app"
wit="external:agents.jetpack.frontend.frontend_wit:app"
wit_query="external:agents.jetpack.frontend.frontend_queries:app"

[[actors]]
name="chat"
is_prototype=true
push=["./agents/jetpack/chat/chat_messages.html:/templates/chat_messages.html", "./agents/jetpack/chat/artifacts.html:/templates/artifacts.html"]
wit_genesis="external:agents.jetpack.chat.chat_wit:app"
wit="external:agents.jetpack.chat.chat_wit:app"
wit_query="external:agents.jetpack.chat.chat_queries:app"

[[actors]]
name="coder"
is_prototype=true
wit_genesis="external:agents.jetpack.coder.coder_wit:app"
wit="external:agents.jetpack.coder.coder_wit:app"

[[actors]]
name="retriever"
is_prototype=true
wit_genesis="external:agents.jetpack.coder.retriever_wit:app"
wit="external:agents.jetpack.coder.retriever_wit:app"